-- Generated by scripts/generate-seed-migrations.py from
-- reference-data/src/main/resources/seed-data/nigeria-states.json
-- Source: Wikipedia "States of Nigeria" (36 states + FCT, with capitals).
INSERT INTO states (id, country_id, name, level, parent_id, capital)
SELECT gen_random_uuid(), c.id, v.name, 1, NULL, v.capital
FROM (VALUES
    ('Abia', 'Umuahia'),
    ('Adamawa', 'Yola'),
    ('Akwa Ibom', 'Uyo'),
    ('Anambra', 'Awka'),
    ('Bauchi', 'Bauchi'),
    ('Bayelsa', 'Yenagoa'),
    ('Benue', 'Makurdi'),
    ('Borno', 'Maiduguri'),
    ('Cross River', 'Calabar'),
    ('Delta', 'Asaba'),
    ('Ebonyi', 'Abakaliki'),
    ('Edo', 'Benin City'),
    ('Ekiti', 'Ado Ekiti'),
    ('Enugu', 'Enugu'),
    ('Federal Capital Territory', 'Abuja'),
    ('Gombe', 'Gombe'),
    ('Imo', 'Owerri'),
    ('Jigawa', 'Dutse'),
    ('Kaduna', 'Kaduna'),
    ('Kano', 'Kano'),
    ('Katsina', 'Katsina'),
    ('Kebbi', 'Birnin Kebbi'),
    ('Kogi', 'Lokoja'),
    ('Kwara', 'Ilorin'),
    ('Lagos', 'Ikeja'),
    ('Nasarawa', 'Lafia'),
    ('Niger', 'Minna'),
    ('Ogun', 'Abeokuta'),
    ('Ondo', 'Akure'),
    ('Osun', 'Osogbo'),
    ('Oyo', 'Ibadan'),
    ('Plateau', 'Jos'),
    ('Rivers', 'Port Harcourt'),
    ('Sokoto', 'Sokoto'),
    ('Taraba', 'Jalingo'),
    ('Yobe', 'Damaturu'),
    ('Zamfara', 'Gusau')
) AS v(name, capital)
CROSS JOIN (SELECT id FROM countries WHERE iso3 = 'NGA') c;
