#!/usr/bin/env python3
"""Generates Flyway seed migrations from the JSON fixtures under
reference-data/src/main/resources/seed-data/.

Run once after updating a fixture file; it picks the next free Vnnnn
version automatically. Re-running after the generated migrations have
already been applied creates *new* migration files on top (Flyway
migrations are immutable once run) rather than editing old ones - it
never rewrites an existing Vnnnn file.

Usage: python3 scripts/generate-seed-migrations.py
"""
import json
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SEED_DIR = REPO_ROOT / "reference-data/src/main/resources/seed-data"
MIGRATION_DIR = REPO_ROOT / "app/src/main/resources/db/migration"


def next_version():
    existing = [int(m.group(1)) for f in MIGRATION_DIR.glob("V*.sql")
                if (m := re.match(r"V(\d+)__", f.name))]
    return max(existing, default=0) + 1


def sql_str(value):
    return "'" + value.replace("'", "''") + "'"


def write_migration(version, slug, sql):
    path = MIGRATION_DIR / f"V{version:04d}__{slug}.sql"
    path.write_text(sql)
    print(f"wrote {path.relative_to(REPO_ROOT)}")
    return version + 1


def seed_countries(version):
    countries = json.loads((SEED_DIR / "countries.json").read_text())
    values = ",\n    ".join(
        f"(gen_random_uuid(), {sql_str(c['name'])}, {sql_str(c['iso3'])}, "
        f"{sql_str(c['currency'])}, {sql_str(c['flagUrl'])})"
        for c in countries
    )
    sql = (
        "-- Generated by scripts/generate-seed-migrations.py from "
        "reference-data/src/main/resources/seed-data/countries.json\n"
        "-- Source: https://github.com/mledoze/countries (public domain).\n"
        "-- Nigeria already exists from V0001; ON CONFLICT keeps this safe to run\n"
        "-- alongside it rather than needing to special-case exclude it here.\n"
        "INSERT INTO countries (id, name, iso3, currency, flag_url) VALUES\n"
        f"    {values}\n"
        "ON CONFLICT (iso3) DO NOTHING;\n"
    )
    return write_migration(version, "seed_countries", sql)


def seed_nigeria_states(version):
    states = json.loads((SEED_DIR / "nigeria-states.json").read_text())
    values = ",\n    ".join(
        f"({sql_str(s['name'])}, {sql_str(s['capital'])})" for s in states
    )
    sql = (
        "-- Generated by scripts/generate-seed-migrations.py from\n"
        "-- reference-data/src/main/resources/seed-data/nigeria-states.json\n"
        "-- Source: Wikipedia \"States of Nigeria\" (36 states + FCT, with capitals).\n"
        "INSERT INTO states (id, country_id, name, level, parent_id, capital)\n"
        "SELECT gen_random_uuid(), c.id, v.name, 1, NULL, v.capital\n"
        "FROM (VALUES\n"
        f"    {values}\n"
        ") AS v(name, capital)\n"
        "CROSS JOIN (SELECT id FROM countries WHERE iso3 = 'NGA') c;\n"
    )
    return write_migration(version, "seed_nigeria_states", sql)


def seed_nigeria_lgas(version):
    lgas = json.loads((SEED_DIR / "nigeria-lgas.json").read_text())
    values = ",\n    ".join(
        f"({sql_str(l['stateName'])}, {sql_str(l['name'])})" for l in lgas
    )
    sql = (
        "-- Generated by scripts/generate-seed-migrations.py from\n"
        "-- reference-data/src/main/resources/seed-data/nigeria-lgas.json\n"
        "-- Source: https://github.com/xosasx/nigerian-local-government-areas\n"
        "-- (774 LGAs total - the official NPC/INEC count), cross-checked against\n"
        "-- per-state totals published on Wikipedia.\n"
        "-- Depends on V0028 (states must exist as parents) - must run after it.\n"
        "INSERT INTO states (id, country_id, name, level, parent_id)\n"
        "SELECT gen_random_uuid(), s.country_id, v.lga_name, 2, s.id\n"
        "FROM (VALUES\n"
        f"    {values}\n"
        ") AS v(state_name, lga_name)\n"
        "JOIN states s ON s.name = v.state_name AND s.level = 1;\n"
    )
    return write_migration(version, "seed_nigeria_lgas", sql)


def seed_nigeria_banks(version):
    banks = json.loads((SEED_DIR / "nigeria-banks.json").read_text())
    values = ",\n    ".join(
        f"(gen_random_uuid(), {sql_str(b['name'])}, {sql_str(b['code'])})" for b in banks
    )
    sql = (
        "-- Generated by scripts/generate-seed-migrations.py from\n"
        "-- reference-data/src/main/resources/seed-data/nigeria-banks.json\n"
        "-- Source: Paystack's public GET /bank list (api.paystack.co/bank) -\n"
        "-- kept in sync with what the app's own Paystack integration supports\n"
        "-- for transfers/name verification (see BankVerificationGateway).\n"
        "INSERT INTO banks (id, name, code) VALUES\n"
        f"    {values}\n"
        "ON CONFLICT (code) DO NOTHING;\n"
    )
    return write_migration(version, "seed_nigeria_banks", sql)


def main():
    version = next_version()
    version = seed_countries(version)
    version = seed_nigeria_states(version)
    version = seed_nigeria_lgas(version)
    version = seed_nigeria_banks(version)


if __name__ == "__main__":
    main()
